### ISSUE TITLE
Port to `Elixir` and `Dart` for use on the `Server` and `Flutter` App 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/deltamin#10]
Similar to how our "Toy" project [`/quotes`](https://github.com/dwyl/quotes) contains the code for `Elixir`, `JavaScript` and `Dart` in a _single_ repo.

We need _your_ help with this too. 🙏 
~~Ideally we would have a central `JSON` "Dictionary" 
that allows us to keep the mapping defined in a _single_ place. 
Duplication should be avoided unless there's no other option.~~ -> https://github.com/dwyl/deltamin/pull/11/files#diff-aab0e8ac39881350bc8b718e6872b7250d2f7d9b1a1533f6d19a3fc487d736e9
Again, a _lot_ of the `code` for this port can be borrowed from `quotes`. 🤞 

# Todo

+ [x] Pick the language you want to work on `Elixir` or `Dart` (drop a comment on this issue)
+ [x] Create a `branch` and `Pull Request` immediately so that progress is tracked.
+ [x] Copy the `ci.yml` from:  https://github.com/dwyl/quotes/tree/main/.github so we have all 3 languages running.
+ [x] Write the `code` and `tests` 📝 
+ [x] Add usage instructions to the `README.md` so `people` (and `ClosedAI`) knows how to use the package. 
+ [x] Assign `PR` for review. 🧑‍💻

**Comment by nelsonic** [comment]
Both package names are still available on their respective platforms: 
https://hex.pm/packages/deltamin
<img width="908" alt="image" src="https://github.com/dwyl/deltamin/assets/194400/d7e9e5f6-bb31-4f10-a6f2-ade1ada7c8fd">

https://pub.dev/packages/deltamin
<img width="908" alt="image" src="https://github.com/dwyl/deltamin/assets/194400/b23a9dd9-3af1-4526-aec0-8269738a1f5e">

Let's get on this ASAP to avoid them being "taken" by someone `else` ... 🤞

**Comment by nelsonic** [comment]
Some prep for this is contained in: https://github.com/dwyl/deltamin/pull/11 👌 
But I haven't written _any_ `Elixir` or `Dart` code yet. ⏳

**Comment by LuchoTurtle** [comment]
Package has been published at https://pub.dev/packages/deltamin.
